server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: bank-ecommerce-gateway
  cloud:
    gateway:
      routes:
        - id: ecommerce
          uri: lb://ecommerce-service
          predicates:
          - Path=/ecommerce/**
        - id: bank
          uri: lb://bank-service
          predicates:
          - Path=/bank/**